name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: 14
      - name: install package dependencies
        run: yarn
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build package
        run: npm run build
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish package
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14

  #     - name: deploy to GPR
  #       uses: mikeal/merge-release@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_REGISTRY_URL: https://npm.pkg.github.com/
  #         NPM_CONFIG_USERCONFIG: ./.npmrc
